- name: using loops to install packages
  hosts: localhost
  become: yes
  tasks:
    - name: installing packages using loops
      ansible.builtin.psckage:
        msg: "installing packages {{item}}"
        state: present
      loop:
        - git
        - nginx
        - mysql
        - postfix